### ISSUE TITLE
split train for test

### ISSUE THREAD

**Issue by ssd-ls-a** [ScaDS/Match-R-CNN-Repoduction#3]
- Zufällig mit festem Seed 62629 Bilder für test auswählen und aus train entfernen
- alles in neuem Ordner speichern?

**Comment by aehm03** [comment]
Ich würde den Split nicht auf der ebenen von Bildern machen sondern auf der Ebene von Pair_id. Sonst besteht die Gefahr (insbesondere da der Test Split ja klein ist), dass zu wenige passende Paare in test landen.
